// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PreFlight
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPreFlightPackageString = "1a56cc95-5726-44a9-adf7-0ab559f5358e";
        public static Guid guidPreFlightPackage = new Guid(guidPreFlightPackageString);

        public const string guidPreFlightPackageCmdSetString = "1de0447e-97d4-49f2-93d9-df7b6e77cc76";
        public static Guid guidPreFlightPackageCmdSet = new Guid(guidPreFlightPackageCmdSetString);

        public const string guidImagesString = "296f36a8-dcf5-4a36-a2d3-ce3ef89d8d8d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}